### ISSUE TITLE
More robust database saving

### ISSUE THREAD

**Issue by irwineffect** [irwineffect/card_login#1]
Currently the database is saved only when the login program is terminated via SIGINT. The database will not be saved if the program terminates abnormally or due to a SIGHUP (disconnection). 

Also, might be a good idea to save the database periodically via a timer interrupt?

**Comment by bkallaher** [comment]
SIGHUP is fixed with commit d15c4bd.

**Comment by bkallaher** [comment]
Periodic timer interrupt set for every minute in ce788de
